# Docker Swarm deploy file

# multiple services can be defined, and an overworld will be started for each one
# the following config declares 3 worlds  (Overworld, Caves, Foreign)

# exported volumes:
#  - /dst/config        - shard-specific config directory
#  - /dst/mods          - cluster-specific mods directory
#  - /opt/dst_server    - where the server is ultimately installed / running from
#  - /home/dst          - working directory / entrypoints
#
#
# folder structure for /dst:
# /dst
#  /config
#   + worldgenoverride.lua    [required -- controls overall world gen]
#   + cluster.ini             [required -- controls overall cluster]
#   + /Overworld              [required -- one of the shards]
#   +-- server.ini            [required -- settings for this shard]
#   +-- worldgenoverride.lua  [optional -- allows customizing this shard]
#   + /Caves                  [optional -- another shard]
#   +-- server.ini            [required -- settings for this shard]
#   +-- worldgenoverride.lua  [optional -- allows customizing this shard]
#   + /TerrariaCaves          [optional -- another shard]
#   +-- server.ini            [required -- settings for this shard]
#   +-- worldgenoverride.lua  [optional -- allows customizing this shard]
#  /mods
#   + modoverrides.lua
#   + /Overworld              [optional -- will apply the overrides to just the Overworld shard]
#   +-- modoverrides.lua

services:
  dst_overworld:
    hostname: dst_overworld # used in server.ini files for other shards to connect via hostname
    image: bryanboettcher/dst-dedicated-server:latest
    networks:
      - dst_cluster
    ports:
      - 11018:11018/udp   # must match the server.ini for THIS service
    volumes:
      - /mnt/fast/dst:/dst
      - dst_server_overworld:/opt/dst_server
      - dst_home_overworld:/home/dst
    environment:
      - SHARD_NAME=Overworld

    # These allow to stdin when attaching to the container via `docker attach`
    # Any server commands should be sent to the master shard as it manages its slaves (Caves)
    stdin_open: true
    tty: true

  dst_caves:
    hostname: dst_caves
    image: bryanboettcher/dst-dedicated-server:latest
    ports:
      - 11017:11017/udp   # must match the server.ini for THIS service
    networks:
      - dst_cluster
    volumes:
      - /mnt/fast/dst:/dst
      - dst_server_caves:/opt/dst_server
      - dst_home_caves:/home/dst
    environment:
      - SHARD_NAME=Caves

  dst_terraria_caves:
    hostname: terraria_caves
    image: bryanboettcher/dst-dedicated-server:latest
    ports:
      - 11016:11016/udp
    networks:
      - dst_cluster
    volumes:
      - /mnt/fast/dst:/dst
      - dst_server_terraria_caves:/opt/dst_server
      - dst_home_terraria_caves:/home/dst
    environment:
      - SHARD_NAME=TerrariaCaves

networks:
  dst_cluster:

configs:
  dst_overworld_config:
    external: true
  dst_caves_config:
    external: true
  dst_foreign_config:
    external: true